<?php 
/*
Plugin Name: Hody Addon Pro
Plugin URI: https://hodessy.com/addon-pro
Description: Plugin adds custom blocks and advanced features to Hody Themes
Version: 0.0.1
Author: Hodessy
Author URI: https://hodessy.com
Text Domain: hody-pro
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}