<?php
/**
 * Define and import vendors
 *  ### Vendor List and Existing Versions ###
 *  Lazy Block by nK (https://wordpress.org/plugins/lazy-blocks/) V 2.3.4  disabled in favour of genesis blocks
 *  Genesis Custom Block Pro V 1.5.0
 * 	Metabox, by metabox.io (none yet)
 */

/**
  *     Variables to define path and URL.
  */
  define( 'HODYADDON_GEN_PATH', __DIR__ .'/vendor/genesis/' );
  define( 'HODYADDON_BLOCK_DIR', __DIR__ .'/blocks' );
  define( 'HODYADDON_BLOCK_URL',plugins_url( 'blocks/', __FILE__ ) );

  /**
   * Welcome the powerful, Genesisssssss plugin...
   */
  if ( file_exists( HODYADDON_GEN_PATH . 'cbp/cbp.php' ) ) {
    require_once HODYADDON_GEN_PATH . 'cbp/cbp.php';
  }
    
 /**
  *     Declare new Path for Genesis custom blocks to find templates
  */

  function hodyaddongenesis_block_get_alternate_template_path( $path ) {
    unset( $path );
    return __DIR__;
}

add_filter( 'genesis_custom_blocks_template_path', 'hodyaddongenesis_block_get_alternate_template_path' );


/**
 * Init Blocks generated by Genesis custom blocks
 */
if ( file_exists( HODYADDON_BLOCK_DIR . '/hody-genblocks.php' ) ) {
	require_once HODYADDON_BLOCK_DIR . '/hody-genblocks.php';
}

/**
 * Load Block Styles for Genesis
 */
add_action( 'after_setup_theme', 'hodyaddon_gen_style_setup' );
function hodyaddon_gen_style_setup() {

	$styled_genblocks = [ 'accordion','team', 'video-lightbox', 'teammate' ];
	foreach ( $styled_genblocks as $genblock_name ) {
		$args = array(
			'handle' => "hody-core-$genblock_name",
			'src'    => plugins_url(  "assets/css/blocks/$genblock_name.min.css", __FILE__ ),
			'path'   => plugin_dir_path( "assets/css/blocks/$genblock_name.min.css", __FILE__ ),
		);
		// Replace the "core" prefix if you are styling blocks from plugins.
		wp_enqueue_block_style( "genesis-custom-blocks/$genblock_name", $args );
	}

}